#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define GLOBAL_STATUS_REG 0x08

#define WAN_COLOR_R 0x10
#define WAN_COLOR_G 0x11
#define WAN_COLOR_B 0x12
#define WAN_STATUS_REG GLOBAL_STATUS_REG
#define WAN_STATUS_MASK 0x01

#define LAN_COLOR_R 0x13
#define LAN_COLOR_G 0x14
#define LAN_COLOR_B 0x15
#define LAN_STATUS_REG GLOBAL_STATUS_REG
#define LAN_STATUS_MASK 0x01

#define WIFI_COLOR_R 0x16
#define WIFI_COLOR_G 0x17
#define WIFI_COLOR_B 0x18
#define WIFI_STATUS_REG GLOBAL_STATUS_REG
#define WIFI_STATUS_MASK 0x01

#define PWR_COLOR_R 0x19
#define PWR_COLOR_G 0x1A
#define PWR_COLOR_B 0x1B
#define PWR_STATUS_REG GLOBAL_STATUS_REG
#define PWR_STATUS_MASK 0x01

#define BASE_REGISTER 0xFFA00000
#define MAPPED_SIZE 4096

#endif //CONFIGURATION_H
